---------------------------------------------------------------------------------
-- Oraciones
-- Alberto Vera Espitia
-- GeekBucket 2016
---------------------------------------------------------------------------------

-- Mediciones de pantalla
intW = display.contentWidth
intH = display.contentHeight
midW = display.contentCenterX
midH = display.contentCenterY
h = display.topStatusBarContentHeight

-- Colors
cBlack = { 0 }
cGrayL = { .95 }
cWhite = { 1 }
cPurple = { .28, .21, .3 }
cPurpleH = { .21, .16, .23 }
-- Fonts
fMonBold = 'Montserrat'
fMonRegular = 'Montserrat'

-- Arreglos
lstDay = {"Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"}
lstMonth = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}

-- TMP
idxC = 1
idxP = 0
curTime = 1
cntTime = 1
lstDays = {}
--[[lstDays = {
    {day = '', noDate = '', month = '', title = 'Corona de la Divina Misericordia', subtitle = 'Este día rezamos acompañados de los Misterios Dolorosos', file = '16-5TO-29-1L-C.mp3', fav = false, detail = 'Señor, en el silencio de este día que nace,\nvengo a pedirte paz, sabiduría y fuerza.\n\nHoy quiero mirar al mundo con ojos llenos de amor.\nSer paciente, comprensivo, humilde, suave y bueno.\n\nVer a tus hijos detrás de las apariencias,\ncomo los ves tu mismo,\npara así poder apreciar la bondad de cada uno.\n\nCierra mis oídos a toda murmuración.\nGuarda mi lengua de toda maledicencia.\nQue sólo los pensamientos que bendigan permanezcan en mi.\n\nQuiero ser tan bienintencionado y bueno\nque todos los que se acerquen a mi sientan tu presencia.\nRevísteme de tu bondad señor\ny haz que en este día yo te refleje.'},
    {day = '', noDate = '', month = '', title = 'Sagrado Corazón de Jesús', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = '16-5TO-29-3X-C.mp3', fav = false, detail = 'Señor mio, Jesucristo, \nDios y Hombre verdadero, Creador, Padre y Redentor mío, \npor ser Vos quién sois y porque os amo sobre todas las cosas, me pesa de todo corazón haberos ofendido; \npropongo firmemente nunca más pecar, \napartarme de todas las ocaciones de ofenderos, \nconfesarme y, cumplir la penitencia que me fuera impuesta.\n\nOfrezco, Señor, mi vida, obras y trabajos, \nen satisfacción de todos mis pecados, y, así como lo suplico, así confío en vuestra bondad y misericordia infinita, \nque los perdonareis, por los méritos de vuestra preciosísima sangre, pasión y muerte, y me dareis gracia para enmendarme, y perseverar en vuestro santo amor y servicio,\n hasta el fin de mi vida.\nAmén.'},
    {day = '', noDate = '', month = '', title = 'Rosario de la Liberación', subtitle = 'Este día rezamos Misterios Gloriosos', file = '16-5TO-29-4J-C.mp3', fav = false, detail = 'Yo confieso ante Dios Todopoderoso, y ante ustedes hermanos que he pecado mucho de pensamiento, palabra, obra y omisión.\n\nPor mi culpa, por mi culpa, por mi gran culpa.\n\nPor eso ruego a Santa María siempre Virgen, a los ángeles, a los santos y a ustedes hermanos, que intercedan por mí ante Dios, Nuestro Señor. Amén.'},
    {day = '', noDate = '', month = '', title = 'Virgen de Guadalupe', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = '16-5TO-29-5V-C.mp3', fav = true, detail = 'Gloria a Dios en el cielo,\ny en la tierra paz a los hombres que ama el Señor.\n\nPor tu inmensa gloria te alabamos,\nte bendecimos, te adoramos,\nte glorificamos, te damos gracias,\nSeñor Dios, Rey celestial,\nDios Padre todopoderoso Señor,\nHijo único, Jesucristo.\n\nSeñor Dios, Cordero de Dios, Hijo del Padre;\ntú que quitas el pecado del mundo,\nten piedad de nosotros;\ntú que quitas el pecado del mundo,\natiende nuestra súplica;\ntú que estás sentado a la derecha del Padre,\nten piedad de nosotros;\nporque sólo tú eres Santo,\nsólo tú Señor, sólo tú Altísimo, Jesucristo,\ncon el Espíritu Santo en la gloria de Dios Padre.'},
    {day = '', noDate = '', month = '', title = 'Caminata de la Encarnación', subtitle = 'Rezamos el rosario de la divina misericordia', file = 'rOraCast_-16-5TO-30-0D-2.mp3', fav = false, detail = 'Señor, en el silencio de este día que nace,\nvengo a pedirte paz, sabiduría y fuerza.\n\nHoy quiero mirar al mundo con ojos llenos de amor.\nSer paciente, comprensivo, humilde, suave y bueno.\n\nVer a tus hijos detrás de las apariencias,\ncomo los ves tu mismo,\npara así poder apreciar la bondad de cada uno.\n\nCierra mis oídos a toda murmuración.\nGuarda mi lengua de toda maledicencia.\nQue sólo los pensamientos que bendigan permanezcan en mi.\n\nQuiero ser tan bienintencionado y bueno\nque todos los que se acerquen a mi sientan tu presencia.\nRevísteme de tu bondad señor\ny haz que en este día yo te refleje.'},
    {day = '', noDate = '', month = '', title = 'Oración a María Santísima, Salud de los Enfermos', subtitle = 'Misterios Luminosos', file = '16-5TO-30-1L-C.mp3', fav = false, detail = 'Señor mio, Jesucristo, \nDios y Hombre verdadero, Creador, Padre y Redentor mío, \npor ser Vos quién sois y porque os amo sobre todas las cosas, me pesa de todo corazón haberos ofendido; \npropongo firmemente nunca más pecar, \napartarme de todas las ocaciones de ofenderos, \nconfesarme y, cumplir la penitencia que me fuera impuesta.\n\nOfrezco, Señor, mi vida, obras y trabajos, \nen satisfacción de todos mis pecados, y, así como lo suplico, así confío en vuestra bondad y misericordia infinita, \nque los perdonareis, por los méritos de vuestra preciosísima sangre, pasión y muerte, y me dareis gracia para enmendarme, y perseverar en vuestro santo amor y servicio,\n hasta el fin de mi vida.\nAmén.'},
    {day = '', noDate = '', month = '', title = 'Rosario de la Liberación', subtitle = 'Este día rezamos Misterios Gloriosos', file = '16-5TO-30-2M-C.mp3', fav = false, detail = 'Yo confieso ante Dios Todopoderoso, y ante ustedes hermanos que he pecado mucho de pensamiento, palabra, obra y omisión.\n\nPor mi culpa, por mi culpa, por mi gran culpa.\n\nPor eso ruego a Santa María siempre Virgen, a los ángeles, a los santos y a ustedes hermanos, que intercedan por mí ante Dios, Nuestro Señor. Amén.'},
    {day = '', noDate = '', month = '', title = 'Oración a la Divina Pastora', subtitle = 'Este día rezamos la caminata de la encarnación', file = '16-5TO-30-3X-C.mp3', fav = true, detail = 'Gloria a Dios en el cielo,\ny en la tierra paz a los hombres que ama el Señor.\n\nPor tu inmensa gloria te alabamos,\nte bendecimos, te adoramos,\nte glorificamos, te damos gracias,\nSeñor Dios, Rey celestial,\nDios Padre todopoderoso Señor,\nHijo único, Jesucristo.\n\nSeñor Dios, Cordero de Dios, Hijo del Padre;\ntú que quitas el pecado del mundo,\nten piedad de nosotros;\ntú que quitas el pecado del mundo,\natiende nuestra súplica;\ntú que estás sentado a la derecha del Padre,\nten piedad de nosotros;\nporque sólo tú eres Santo,\nsólo tú Señor, sólo tú Altísimo, Jesucristo,\ncon el Espíritu Santo en la gloria de Dios Padre.'},
    {day = '', noDate = '', month = '', title = 'Oración a Nuestra Señora de Fátima', subtitle = 'Este día rezamos Misterios Gloriosos', file = '16-5TO-30-4J-C.mp3', fav = true, detail = 'Señor, en el silencio de este día que nace,\nvengo a pedirte paz, sabiduría y fuerza.\n\nHoy quiero mirar al mundo con ojos llenos de amor.\nSer paciente, comprensivo, humilde, suave y bueno.\n\nVer a tus hijos detrás de las apariencias,\ncomo los ves tu mismo,\npara así poder apreciar la bondad de cada uno.\n\nCierra mis oídos a toda murmuración.\nGuarda mi lengua de toda maledicencia.\nQue sólo los pensamientos que bendigan permanezcan en mi.\n\nQuiero ser tan bienintencionado y bueno\nque todos los que se acerquen a mi sientan tu presencia.\nRevísteme de tu bondad señor\ny haz que en este día yo te refleje.'}, 
    {day = '', noDate = '', month = '', title = 'Santa María Madre de Jesucristo', subtitle = 'Este día rezamos el sermón de las siete palabras', file = '16-5TO-31-0D-2.mp3', fav = false, detail = 'Señor mio, Jesucristo, \nDios y Hombre verdadero, Creador, Padre y Redentor mío, \npor ser Vos quién sois y porque os amo sobre todas las cosas, me pesa de todo corazón haberos ofendido; \npropongo firmemente nunca más pecar, \napartarme de todas las ocaciones de ofenderos, \nconfesarme y, cumplir la penitencia que me fuera impuesta.\n\nOfrezco, Señor, mi vida, obras y trabajos, \nen satisfacción de todos mis pecados, y, así como lo suplico, así confío en vuestra bondad y misericordia infinita, \nque los perdonareis, por los méritos de vuestra preciosísima sangre, pasión y muerte, y me dareis gracia para enmendarme, y perseverar en vuestro santo amor y servicio,\n hasta el fin de mi vida.\nAmén.'},
    {day = '', noDate = '', month = '', title = 'Sagrado Corazón de Jesús', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = '16-5TO-29-1L-C.mp3', fav = false, detail = 'Yo confieso ante Dios Todopoderoso, y ante ustedes hermanos que he pecado mucho de pensamiento, palabra, obra y omisión.\n\nPor mi culpa, por mi culpa, por mi gran culpa.\n\nPor eso ruego a Santa María siempre Virgen, a los ángeles, a los santos y a ustedes hermanos, que intercedan por mí ante Dios, Nuestro Señor. Amén.'},
    {day = '', noDate = '', month = '', title = 'Trisagio Santísima Trinidad', subtitle = 'Rezamos el rosario de la divina misericordia', file = 'rOraCast_-16-5TO-29-2M-C.mp3', fav = true, detail = 'Gloria a Dios en el cielo,\ny en la tierra paz a los hombres que ama el Señor.\n\nPor tu inmensa gloria te alabamos,\nte bendecimos, te adoramos,\nte glorificamos, te damos gracias,\nSeñor Dios, Rey celestial,\nDios Padre todopoderoso Señor,\nHijo único, Jesucristo.\n\nSeñor Dios, Cordero de Dios, Hijo del Padre;\ntú que quitas el pecado del mundo,\nten piedad de nosotros;\ntú que quitas el pecado del mundo,\natiende nuestra súplica;\ntú que estás sentado a la derecha del Padre,\nten piedad de nosotros;\nporque sólo tú eres Santo,\nsólo tú Señor, sólo tú Altísimo, Jesucristo,\ncon el Espíritu Santo en la gloria de Dios Padre.'},
    {day = '', noDate = '', month = '', title = 'Oración a Nuestra Señora de Fátima', subtitle = 'Misterios Luminosos', file = '16-5TO-29-3X-C.mp3', fav = true, detail = 'Señor, en el silencio de este día que nace,\nvengo a pedirte paz, sabiduría y fuerza.\n\nHoy quiero mirar al mundo con ojos llenos de amor.\nSer paciente, comprensivo, humilde, suave y bueno.\n\nVer a tus hijos detrás de las apariencias,\ncomo los ves tu mismo,\npara así poder apreciar la bondad de cada uno.\n\nCierra mis oídos a toda murmuración.\nGuarda mi lengua de toda maledicencia.\nQue sólo los pensamientos que bendigan permanezcan en mi.\n\nQuiero ser tan bienintencionado y bueno\nque todos los que se acerquen a mi sientan tu presencia.\nRevísteme de tu bondad señor\ny haz que en este día yo te refleje.'},
    {day = '', noDate = '', month = '', title = 'Santa María Madre de Jesucristo', subtitle = 'Este día rezamos el sermón de las siete palabras', file = '16-5TO-31-0D-2.mp3', fav = false, detail = 'Señor mio, Jesucristo, \nDios y Hombre verdadero, Creador, Padre y Redentor mío, \npor ser Vos quién sois y porque os amo sobre todas las cosas, me pesa de todo corazón haberos ofendido; \npropongo firmemente nunca más pecar, \napartarme de todas las ocaciones de ofenderos, \nconfesarme y, cumplir la penitencia que me fuera impuesta.\n\nOfrezco, Señor, mi vida, obras y trabajos, \nen satisfacción de todos mis pecados, y, así como lo suplico, así confío en vuestra bondad y misericordia infinita, \nque los perdonareis, por los méritos de vuestra preciosísima sangre, pasión y muerte, y me dareis gracia para enmendarme, y perseverar en vuestro santo amor y servicio,\n hasta el fin de mi vida.\nAmén.'},
}]]
