---------------------------------------------------------------------------------
-- Oraciones
-- Alberto Vera Espitia
-- GeekBucket 2016
---------------------------------------------------------------------------------

-- Mediciones de pantalla
intW = display.contentWidth
intH = display.contentHeight
midW = display.contentCenterX
midH = display.contentCenterY
h = display.topStatusBarContentHeight

-- Colors
cBlack = { 0 }
cGrayL = { .95 }
cWhite = { 1 }
cPurple = { .28, .21, .3 }
cPurpleH = { .21, .16, .23 }

-- Fonts
fMonBold = 'Montserrat'
fMonRegular = 'Montserrat'

-- Arreglos
lstDay = {"Domingo", "Lunes", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"}
lstMonth = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"}

-- TMP
lstDays = {
    {day = '', noDate = '', month = '', title = 'Corona de la Divina Misericordia', subtitle = 'Este día rezamos acompañados de los Misterios Dolorosos', file = 'Rosario_Misterios_Dolorosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.'},
    {day = '', noDate = '', month = '', title = 'Rosario del Perdón', subtitle = 'Este día rezamos la caminata de la encarnación', file = 'Caminata_de_la_Encarnacin.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi.'},
    {day = '', noDate = '', month = '', title = 'Sagrado Corazón de Jesús', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = 'Rosario_Misterios_Gozosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.'},
    {day = '', noDate = '', month = '', title = 'Rosario de la Liberación', subtitle = 'Este día rezamos Misterios Gloriosos', file = 'Rosario_Misterios_Gloriosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. '},
    {day = '', noDate = '', month = '', title = 'Virgen de Guadalupe', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = 'Rosario_Misterios_Gozosos.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.'},
    {day = '', noDate = '', month = '', title = 'Caminata de la Encarnación', subtitle = 'Rezamos el rosario de la divina misericordia', file = 'rOraCast_-_Rosario_de_la_Divina_Misericordia.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. '},
    {day = '', noDate = '', month = '', title = 'Oración a María Santísima, Salud de los Enfermos', subtitle = 'Misterios Luminosos', file = 'Rosario_Misterios_Luminosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.'},
    {day = '', noDate = '', month = '', title = 'Rosario de la Liberación', subtitle = 'Este día rezamos Misterios Gloriosos', file = 'Rosario_Misterios_Gloriosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. '},
    {day = '', noDate = '', month = '', title = 'Oración a la Divina Pastora', subtitle = 'Este día rezamos la caminata de la encarnación', file = 'Caminata_de_la_Encarnacin.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.'},
    {day = '', noDate = '', month = '', title = 'Oración a Nuestra Señora de Fátima', subtitle = 'Este día rezamos Misterios Gloriosos', file = 'Rosario_Misterios_Gloriosos.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. '}, 
    {day = '', noDate = '', month = '', title = 'Santa María Madre de Jesucristo', subtitle = 'Este día rezamos el sermón de las siete palabras', file = 'El_Sermn_de_las_Siete_Palabras.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.'},
    {day = '', noDate = '', month = '', title = 'Sagrado Corazón de Jesús', subtitle = 'Este día rezamos acompañados de los Misterios Gozosos', file = 'Rosario_Misterios_Gozosos.mp3', fav = false, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu.'},
    {day = '', noDate = '', month = '', title = 'Trisagio Santísima Trinidad', subtitle = 'Rezamos el rosario de la divina misericordia', file = 'rOraCast_-_Rosario_de_la_Divina_Misericordia.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo, fringilla vel, aliquet nec, vulputate eget, arcu. In enim justo, rhoncus ut, imperdiet a, venenatis vitae, justo. Nullam dictum felis eu pede mollis pretium. Integer tincidunt. Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim. '},
    {day = '', noDate = '', month = '', title = 'Oración a Nuestra Señora de Fátima', subtitle = 'Misterios Luminosos', file = 'Rosario_Misterios_Luminosos.mp3', fav = true, detail = 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim.'}
}
